### ISSUE TITLE
moonlite.cpp setTemperatureCalibration/setTemperatureCoefficient bug

### ISSUE THREAD

**Issue by tgghtp** [indilib/indi#1169]
In  moonlite.cpp the value handling  for  setTemperatureCalibration and setTemperatureCoefficient
ist wrong. The values to send should be int8_t instead of uint8_t,
see https://indilib.org/media/kunena/attachments/1/HighResSteppermotor107.pdf, SCXX and POXX.

In Moonlite Control Panel, Options Tab you can enter the values in a range from -20...20, but negative values are always sent as 0.

Debug mode:
22:42:41.673: T. Settings Calibration=-5 Coefficient=-5 
22:42:41.757: [DEBUG] CMD <:PO00#>  <=== should be :POF6#
22:42:41.759: [DEBUG] CMD <:SC00#>  <=== should be :POF6#

22:45:20.177: T. Settings Calibration=5 Coefficient=5 
22:45:20.266: [DEBUG] CMD <:PO0A#>
22:45:20.269: [DEBUG] CMD <:SC0A#>

**Comment by TallFurryMan** [comment]
Sorry for missing this, we were focused on the absolute position and the temperature parameters went through.


The problem is the difference in conversion based on processor architecture, as illustrated by https://stackoverflow.com/questions/4752315/coercing-float-into-unsigned-char-on-arm-vs-intel/4752947#4752947. We may have the issue at some other places.


Leaving the implicit conversion like @knro did is a solution, but it has its issues. Apparently we should explicitly convert and clamp the decimal to the `uint8_t` range first before casting.

**Comment by knro** [comment]
@TallFurryMan You're absolutely right! it didn't work on armhf. I just pushed another fix that should work on all architectures. Thanks for noting this!

**Comment by tgghtp** [comment]
same error in moonlite_dro.cpp:

10:17:20.828: FOCUS_TEMPERATURE_SETTINGS Calibration=-3 Coefficient=-5 
10:17:21.063: [DEBUG] CMD <:POFFF>  <= negative always set FFF
10:17:21.066: [DEBUG] CMD <:SCFFF>

10:17:51.196: FOCUS_TEMPERATURE_SETTINGS Calibration=3 Coefficient=5 
10:17:51.377: [DEBUG] CMD <:PO06#>
10:17:51.387: [DEBUG] CMD <:SC0A#>

**Comment by TallFurryMan** [comment]
We may want to create a helper function for this very specific issue. A set of conversion functions.
