### ISSUE TITLE
UART serial connection is not working

### ISSUE THREAD

**Issue by T-STUDIO** [indilib/indi#1640]
From Ver1.9.4, UART serial connection is not working with some drivers.

The serial is recognized, but the driver cannot be connected.

The driver I have confirmed this phenomenon is as follows.

・ SkyWatcher-ALTAZ
・ Celestron AUX

**Comment by knro** [comment]
What does the log say exactly?

**Comment by T-STUDIO** [comment]
Logs cannot be retrieved because the mount cannot be connected.

As I mentioned in the forum, the serial is recognized, but I can no longer connect to the mount.

I want a rollback option as 1.9.3 worked best. .. .. (Returned to 1.9.21 with backup. I also tried 1.9.5 but can't connect.)

**Comment by T-STUDIO** [comment]
I have sent logs on the forum several times.

**Comment by Nekomeshi** [comment]
I found the latest SkyWatcher-ALTAZ driver doesn't follow the Skywatcher's serial communication protocol.
I compared skywatcherAPI.cpp of master branch and V1.9.2, and it has been updated, especially in TalkwithAxis() that is a  function to communicate with telescope.
I wrote the detail in my blog. I'm afraid but the English is poor because it is translated into English  by Google.

https://nekomeshi312-livedoor-blog.translate.goog/archives/14371265.html?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp

**Comment by knro** [comment]
Thank you, can you [enable mount logging in Ekos](https://indilib.org/individuals/logs-howto.html)? Edit your equipment profile and then turn off "Auto Connect". Save your profile and then start it. After it fails to connect to the mount, attach the log file here.

**Comment by T-STUDIO** [comment]
SkyWatcher-ALTAZ
https://indilib.org/forum/mounts/11411-skywatcher-virtuso-will-not-be-reconnected-in-ver1-9-4.html

indi_celestron_aux
https://indilib.org/forum/development/8246-indi-celestron-aux.html?start=252#83410

The logs are here.

As Mr.Nekomeshi mentioned, the new driver has a mount check feature that causes some mounts to stop working.

**Comment by knro** [comment]
I believe this is already fixed in master, can you test?

**Comment by Nekomeshi** [comment]
Yes, it is my pull request.
